ALTER TABLE `notifications` ADD `targetEmployee` varchar(128);--> statement-breakpoint
CREATE INDEX `activity_log_created_at_idx` ON `activity_log` (`createdAt`);--> statement-breakpoint
CREATE INDEX `activity_log_user_id_idx` ON `activity_log` (`userId`);--> statement-breakpoint
CREATE INDEX `anti_corruption_reports_employee_idx` ON `anti_corruption_reports` (`employee`);--> statement-breakpoint
CREATE INDEX `appointments_employee_date_idx` ON `appointments` (`employee`,`appointmentDate`);--> statement-breakpoint
CREATE INDEX `appointments_employee_status_idx` ON `appointments` (`employee`,`appointmentStatus`);--> statement-breakpoint
CREATE INDEX `appointments_date_status_idx` ON `appointments` (`appointmentDate`,`appointmentStatus`);--> statement-breakpoint
CREATE INDEX `audit_log_table_record_idx` ON `audit_log` (`tableName`,`recordId`);--> statement-breakpoint
CREATE INDEX `audit_log_created_at_idx` ON `audit_log` (`createdAt`);--> statement-breakpoint
CREATE INDEX `bank_properties_employee_idx` ON `bank_properties` (`employee`);--> statement-breakpoint
CREATE INDEX `case_attachments_case_table_idx` ON `case_attachments` (`caseId`,`tableName`);--> statement-breakpoint
CREATE INDEX `cases_employee_idx` ON `cases` (`employee`);--> statement-breakpoint
CREATE INDEX `cases_type_idx` ON `cases` (`type`);--> statement-breakpoint
CREATE INDEX `cases_employee_type_idx` ON `cases` (`employee`,`type`);--> statement-breakpoint
CREATE INDEX `cases_case_status_idx` ON `cases` (`caseStatus`);--> statement-breakpoint
CREATE INDEX `cases_created_at_idx` ON `cases` (`createdAt`);--> statement-breakpoint
CREATE INDEX `chat_messages_recipient_idx` ON `chat_messages` (`recipientId`);--> statement-breakpoint
CREATE INDEX `chat_messages_recipient_read_idx` ON `chat_messages` (`recipientId`,`isRead`);--> statement-breakpoint
CREATE INDEX `chat_messages_sender_recipient_idx` ON `chat_messages` (`senderId`,`recipientId`);--> statement-breakpoint
CREATE INDEX `compensation_cases_employee_idx` ON `compensation_cases` (`employee`);--> statement-breakpoint
CREATE INDEX `correspondence_type_employee_archived_idx` ON `correspondence` (`type`,`employee`,`archived`);--> statement-breakpoint
CREATE INDEX `correspondence_employee_idx` ON `correspondence` (`employee`);--> statement-breakpoint
CREATE INDEX `correspondence_parent_id_idx` ON `correspondence` (`parentId`);--> statement-breakpoint
CREATE INDEX `correspondence_received_date_idx` ON `correspondence` (`receivedDate`);--> statement-breakpoint
CREATE INDEX `correspondence_status_archived_idx` ON `correspondence` (`correspondenceStatus`,`archived`);--> statement-breakpoint
CREATE INDEX `correspondence_assignments_correspondence_id_idx` ON `correspondence_assignments` (`correspondenceId`);--> statement-breakpoint
CREATE INDEX `correspondence_assignments_assigned_to_idx` ON `correspondence_assignments` (`assignedTo`);--> statement-breakpoint
CREATE INDEX `correspondence_trail_correspondence_id_idx` ON `correspondence_trail` (`correspondenceId`);--> statement-breakpoint
CREATE INDEX `custom_section_records_section_id_idx` ON `custom_section_records` (`sectionId`);--> statement-breakpoint
CREATE INDEX `debt_actions_debt_id_idx` ON `debt_actions` (`debtId`);--> statement-breakpoint
CREATE INDEX `debt_installments_debt_id_idx` ON `debt_installments` (`debtId`);--> statement-breakpoint
CREATE INDEX `debt_installments_status_idx` ON `debt_installments` (`installmentStatus`);--> statement-breakpoint
CREATE INDEX `debt_payments_debt_id_idx` ON `debt_payments` (`debtId`);--> statement-breakpoint
CREATE INDEX `debts_branch_idx` ON `debts` (`branch`);--> statement-breakpoint
CREATE INDEX `debts_status_idx` ON `debts` (`debtStatus`);--> statement-breakpoint
CREATE INDEX `debts_priority_idx` ON `debts` (`debtPriority`);--> statement-breakpoint
CREATE INDEX `debts_branch_status_idx` ON `debts` (`branch`,`debtStatus`);--> statement-breakpoint
CREATE INDEX `forged_checks_employee_idx` ON `forged_checks` (`employee`);--> statement-breakpoint
CREATE INDEX `general_files_employee_idx` ON `general_files` (`employee`);--> statement-breakpoint
CREATE INDEX `investigation_cases_employee_idx` ON `investigation_cases` (`employee`);--> statement-breakpoint
CREATE INDEX `legal_reviews_created_by_idx` ON `legal_reviews` (`createdBy`);--> statement-breakpoint
CREATE INDEX `legal_reviews_assigned_to_id_idx` ON `legal_reviews` (`assignedToId`);--> statement-breakpoint
CREATE INDEX `legal_reviews_status_idx` ON `legal_reviews` (`reviewStatus`);--> statement-breakpoint
CREATE INDEX `mortgaged_properties_employee_idx` ON `mortgaged_properties` (`employee`);--> statement-breakpoint
CREATE INDEX `notifications_user_id_idx` ON `notifications` (`userId`);--> statement-breakpoint
CREATE INDEX `notifications_user_read_idx` ON `notifications` (`userId`,`isRead`);--> statement-breakpoint
CREATE INDEX `notifications_target_employee_idx` ON `notifications` (`targetEmployee`);--> statement-breakpoint
CREATE INDEX `notifications_user_related_type_idx` ON `notifications` (`userId`,`relatedId`,`type`);--> statement-breakpoint
CREATE INDEX `pending_operations_status_idx` ON `pending_operations` (`status`);--> statement-breakpoint
CREATE INDEX `pending_operations_submitted_by_idx` ON `pending_operations` (`submittedBy`);--> statement-breakpoint
CREATE INDEX `personal_guarantees_employee_idx` ON `personal_guarantees` (`employee`);