/** تسميات أنواع العمليات في سجل النشاط */
export const ACTIVITY_ACTION_LABELS: Record<string, string> = {
  login: "تسجيل دخول",
  login_mobile: "تسجيل دخول (موبايل)",
  change_password: "تغيير كلمة المرور",
  create_user: "إنشاء مستخدم",
  update_user: "تحديث مستخدم",
  reset_password: "إعادة تعيين كلمة المرور",
  create_case: "إضافة قضية",
  update_case: "تعديل قضية",
  delete_case: "حذف قضية",
  archive_case: "أرشفة قضية",
  reassign_case: "تدوير قضية",
  transfer_case: "تحويل قضية",
  create_case_mobile: "إضافة قضية (موبايل)",
  create_case_mobile_pending: "طلب إضافة قضية (موبايل)",
  update_case_mobile: "تعديل قضية (موبايل)",
  update_case_mobile_pending: "طلب تعديل قضية (موبايل)",
  delete_case_mobile: "حذف قضية (موبايل)",
  delete_case_mobile_pending: "طلب حذف قضية (موبايل)",
  create_record: "إضافة سجل",
  update_record: "تعديل سجل",
  delete_record: "حذف سجل",
  bulk_delete_record: "حذف جماعي",
  bulk_delete_record_request: "طلب حذف جماعي",
  approve_pending: "موافقة على طلب",
  reject_pending: "رفض طلب",
  create_correspondence: "إضافة مراسلة",
  update_correspondence: "تحديث مراسلة",
  delete_correspondence: "حذف مراسلة",
  archive_correspondence: "أرشفة مراسلة",
  bulk_delete_correspondence: "حذف مراسلات",
  assign_correspondence: "إحالة مراسلة",
  add_trail: "تتبع مراسلة",
  create_appointment: "إضافة موعد",
  update_appointment: "تحديث موعد",
  delete_appointment: "حذف موعد",
  bulk_delete_appointments: "حذف مواعيد",
  create_legal_review: "إنشاء طلب مراجعة",
  update_legal_review: "تحديث طلب مراجعة",
  delete_legal_review: "حذف طلب مراجعة",
  approve_legal_review: "موافقة مراجعة",
  reject_legal_review: "رفض مراجعة",
  add_legal_review_trail: "تتبع طلب مراجعة",
  submit_legal_review_followup: "تقديم متابعة مراجعة",
  approve_legal_review_followup: "موافقة متابعة مراجعة",
  reject_legal_review_followup: "رفض متابعة مراجعة",
  create_custom_section: "إنشاء قسم مخصص",
  delete_custom_section: "حذف قسم مخصص",
  bulk_delete_custom_records: "حذف سجلات مخصصة",
  update_section_config: "تعديل إعدادات قسم",
  reorder_sections: "إعادة ترتيب الأقسام",
  add_column: "إضافة عمود",
  remove_column: "حذف عمود",
  rename_column: "تغيير اسم عمود",
  import_data: "استيراد بيانات",
  import_builtin: "استيراد قسم مدمج",
  update_settings: "تحديث إعدادات المظهر",
  create_case_type: "إضافة نوع قضية",
  delete_case_type: "حذف نوع قضية",
  view_chat: "عرض المحادثات",
  send_message: "إرسال رسالة",
};

export const ACTIVITY_ACTION_OPTIONS = Object.entries(ACTIVITY_ACTION_LABELS).map(([value, label]) => ({
  value,
  label,
}));

export const AUDIT_TABLE_LABELS: Record<string, string> = {
  cases: "القضايا",
  compensation_cases: "قضايا التضمين",
  investigation_cases: "القضايا التحقيقية",
  personal_guarantees: "الكفالات الشخصية",
  bank_properties: "عقارات المصرف",
  mortgaged_properties: "العقارات المرهونة",
  general_files: "الملفات العامة",
  forged_checks: "الصكوك المزورة",
  case_attachments: "المرفقات",
  correspondence: "المراسلات",
};
